export const ActionTypes = {
  /*
    Search Actions
  */
  REQUEST_SEARCH_ITEMS: 'REQUEST_SEARCH_ITEMS',
  RECEIVE_SEARCH_ITEMS_SUCCESS: 'RECEIVE_SEARCH_ITEMS_SUCCESS',
  RECEIVE_SEARCH_ITEMS_ERROR: 'RECEIVE_SEARCH_ITEMS_ERROR',


  /*
    Item Entity Actions
  */
  INIT_ITEM: 'INIT_ITEM',
  SET_ITEM_PROPERTY: 'SET_ITEM_PROPERTY',

  REQUEST_LOAD_ITEM: 'REQUEST_LOAD_ITEM',
  RECEIVE_LOAD_ITEM_SUCCESS: 'RECEIVE_LOAD_ITEM_SUCCESS',
  RECEIVE_LOAD_ITEM_ERROR: 'RECEIVE_LOAD_ITEM_ERROR',

  REQUEST_SAVE_ITEM: 'REQUEST_SAVE_ITEM',
  RECEIVE_SAVE_ITEM_SUCCESS: 'RECEIVE_SAVE_ITEM_SUCCESS',
  RECEIVE_SAVE_ITEM_ERROR: 'RECEIVE_SAVE_ITEM_ERROR',


  /*
    Raw API Action
  */
  CALL_API: 'CALL_API'
};
